CREATE TABLE EMP_AUDIT
(
	SR_NO INT PRIMARY KEY AUTO_INCREMENT,
    ENUM CHAR(4),
    USER VARCHAR(25),
    TIME_STAMP DATETIME,
    REMARK VARCHAR(200)
);
SELECT * FROM EMP_AUDIT
ORDER BY SR_NO DESC;

TRUNCATE TABLE EMP_AUDIT;
DROP TABLE EMP_AUDIT;

