DROP TABLE PROD;
DROP PROCEDURE PRODUCTION_REQUEST;
DROP PROCEDURE CHECK_AVAILABILITY;
DROP TABLE ORDERS;
DROP PROCEDURE OLD_ORDER_ENTRY;
DROP PROCEDURE NEW_ORDER_ENTRY;
DROP PROCEDURE ORDER_STATUS_UPDATE;
DROP TABLE CUST;
DROP PROCEDURE CUST_SALESMAN_ALLOCATION;
DROP TABLE INCM_EXP_TALLY;
DROP PROCEDURE MONTHLY_EXP;
DROP FUNCTION TOTSALCAL;
DROP PROCEDURE SALES_COMMISSION;
DROP PROCEDURE MONTHLY_SAL;
DROP TABLE EMP_AUDIT;
DROP TABLE SALESMAN;
DROP TABLE EMP_DETAILS;
DROP TABLE EMP;
DROP TABLE DEPT;













