CREATE TABLE DEPT
(
	DEPTNO CHAR(1) PRIMARY KEY,
	DNAME VARCHAR(25) NOT NULL,
	MANAGER CHAR(4),
	EX1 FLOAT,
	EX2 VARCHAR(25)   
);
SELECT * FROM DEPT;
TRUNCATE TABLE DEPT;
DROP TABLE DEPT;

INSERT INTO DEPT (DEPTNO, DNAME, MANAGER)VALUES
('F','FINANCE','F001'),
('R','R & D','R001'),
('P','PRODUCTION','P001'),
('S','SALES','S001');