CREATE TABLE INCM_EXP_TALLY
(
	HEAD CHAR(1)
    CONSTRAINT CH_INCM_EXP_TALLY_HEAD CHECK (HEAD IN ('I', 'E', 'P', 'L')),
    AMT FLOAT,
    ENTRY_DATE DATETIME,
    REMARK VARCHAR(200) 
);
SELECT * FROM INCM_EXP_TALLY ORDER BY ENTRY_DATE DESC;


TRUNCATE TABLE INCM_EXP_TALLY;
DROP TABLE INCM_EXP_TALLY;


DELIMITER //
CREATE PROCEDURE MONTHLY_EXP(MON VARCHAR(15), ELE FLOAT, RENT FLOAT, MISC FLOAT)
BEGIN
	DECLARE EXP FLOAT;
    DECLARE INC FLOAT;
    DECLARE BALANCE FLOAT;
    DECLARE SALARY FLOAT;
    INSERT INTO INCM_EXP_TALLY VALUES ('E', ELE, SYSDATE(), CONCAT(MONTHNAME(SYSDATE()),'-',YEAR(SYSDATE()), ' ELECTRICITY BILL'));
	INSERT INTO INCM_EXP_TALLY VALUES ('E', RENT, SYSDATE(), CONCAT(MONTHNAME(SYSDATE()),'-',YEAR(SYSDATE()), ' RENT EXPENDITURE'));
    INSERT INTO INCM_EXP_TALLY VALUES ('E', MISC, SYSDATE(), CONCAT(MONTHNAME(SYSDATE()),'-',YEAR(SYSDATE()), ' MISCELLANEOUS EXPENDITURE'));
    SELECT SUM(TOTSAL) INTO SALARY FROM EMP;
    INSERT INTO INCM_EXP_TALLY VALUES ('E', SALARY, SYSDATE(), CONCAT(MONTHNAME(SYSDATE()),'-',YEAR(SYSDATE()), ' SALARY OF EMPLOYEES'));
    SELECT SUM(AMT) INTO EXP FROM INCM_EXP_TALLY 
    WHERE HEAD='E' AND MONTHNAME(ENTRY_DATE)=MON AND YEAR(ENTRY_DATE)=YEAR(SYSDATE()) GROUP BY HEAD;
    SELECT SUM(AMT) INTO INC FROM INCM_EXP_TALLY 
    WHERE HEAD='I' AND MONTHNAME(ENTRY_DATE)=MON AND YEAR(ENTRY_DATE)=YEAR(SYSDATE()) GROUP BY HEAD;
    SET BALANCE=INC-EXP;
    IF BALANCE>0 THEN
		INSERT INTO INCM_EXP_TALLY VALUES ('P', BALANCE, SYSDATE(), CONCAT('PROFIT ', MONTHNAME(SYSDATE()),'-',YEAR(SYSDATE())));
	ELSE
        INSERT INTO INCM_EXP_TALLY VALUES ('L', BALANCE, SYSDATE(), CONCAT('LOSS ', MONTHNAME(SYSDATE()),'-',YEAR(SYSDATE())));
    END IF;
END; //
DELIMITER ;
DROP PROCEDURE MONTHLY_EXP;
CALL MONTHLY_EXP('JUNE', 25000, 75000, 102000);

