CREATE TABLE PROD
(
	BATCH_NO INT PRIMARY KEY AUTO_INCREMENT,
	PRO_DATE DATE,
    UNITS INT DEFAULT 500
);
SELECT * FROM PROD ORDER BY PRO_DATE DESC;

TRUNCATE TABLE PROD;
DROP TABLE PROD;

SET @PRO_UNIT=500;
SET @RAW_COST=140;
SET @BASIC_PROD_COST=75;

DELIMITER //
CREATE PROCEDURE PRODUCTION_REQUEST(PDATE DATE)
BEGIN
	DECLARE PROD_COST FLOAT;
    INSERT INTO PROD (PRO_DATE) VALUES (DATE(SYSDATE()));
    SET PROD_COST = @PRO_UNIT*(@BASIC_PROD_COST+@RAW_COST);
    INSERT INTO EMP_AUDIT VALUES (NULL, '0', USER(), SYSDATE(), CONCAT(' PRODUCTION REQUEST PLACED SUCESSFULLY'));
    INSERT INTO INCM_EXP_TALLY VALUES ('E', PROD_COST, PDATE, 'PRODUCTION COST');
END; //
DELIMITER ;
DROP PROCEDURE PRODUCTION_REQUEST;
CALL PRODUCTION_REQUEST('2020-09-01');


DELIMITER //
CREATE PROCEDURE CHECK_AVAILABILITY(ODATE DATE)
BEGIN
	DECLARE PRESENT INT;
    DECLARE REQUIRED INT;
    SELECT SUM(UNITS) INTO PRESENT FROM PROD;
    SELECT SUM(ORDER_UNIT) INTO REQUIRED FROM ORDERS;
    IF(PRESENT-REQUIRED)<0 THEN
		CALL PRODUCTION_REQUEST(ODATE);
    END IF;
END; //
DELIMITER ;
DROP PROCEDURE CHECK_AVAILABILITY;


