CREATE TABLE PROD
(
BATCHNO VARCHAR(20),
PRO_UNIT INT NOT NULL,
PRO_DATE DATE,
PROD_COST FLOAT NOT NULL
);

DELIMITER //
CREATE PROCEDURE PROD1(PRO_UNIT INT,BATCHNO VARCHAR(20),PRO_DATE DATE)
BEGIN
DECLARE PROD_COST FLOAT;
DECLARE OTHER_EXP  FLOAT DEFAULT 200;
DECLARE BASIC_EXP FLOAT DEFAULT 1000;

SET PROD_COST = PRO_UNIT*BASIC_EXP+OTHER_EXP;
INSERT INTO PROD VALUES (BATCHNO,PRO_UNIT,PRO_DATE,PROD_COST);
END; //
DELIMITER ;
DROP PROCEDURE PROD1;

CALL PROD1(25,'123','2020-09-01');
SELECT * FROM PROD;
DROP TABLE PROD;


