CREATE TABLE ORDERS
(
ONUM INT,
CNUM CHAR(2),
SNUM CHAR(2),
ORDER_UNIT INT,
AMT FLOAT,
ORDER_DATE DATE,
STATUSS VARCHAR(25),
BATCH_NO INT

);



DELIMITER //
CREATE PROCEDURE ORDER_TABLE(CNUM CHAR(2), SNUM CHAR(2),ORDER_UNIT INT,ORDER_DATE DATE,STATUSS VARCHAR(25),BATCH_NO INT)
BEGIN
DECLARE ONUM INT;
DECLARE AMT FLOAT;
SET ONUM=FLOOR(RAND()*(100000-0+1))+0;  
SET AMT=30*ORDER_UNIT;
INSERT INTO  ORDERS VALUES(ONUM,CNUM,SNUM,ORDER_UNIT,AMT,ORDER_DATE,STATUSS, BATCH_NO);
END; //
DELIMITER ;


CALL ORDER_TABLE('C1','S1',4,'2022-05-21','DELIVERED',123);
CALL ORDER_TABLE('C2','S2',5,'2022-05-21','PENDING',456);

SELECT * FROM ORDERS;



